FROM python:3.14-slim AS builder

WORKDIR /app
COPY pyproject.toml ./
RUN apt-get update && apt-get install -y gcc libc6-dev --no-install-recommends && rm -rf /var/lib/apt/lists/* && pip install --no-cache-dir poetry && poetry config virtualenvs.create false && poetry lock --no-interaction && poetry install --only main --no-root --no-interaction

FROM python:3.14-slim AS runner

WORKDIR /app
COPY --from=builder /usr/local/lib/python3.14/site-packages /usr/local/lib/python3.14/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
COPY . .

EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
 