FROM node:22-alpine AS builder

WORKDIR /app
COPY tesis-gestkrun-web/package.json tesis-gestkrun-web/pnpm-lock.yaml ./
RUN corepack enable && pnpm install --frozen-lockfile
COPY tesis-gestkrun-web/ .
RUN npm run build

FROM nginx:alpine AS runner
COPY --from=builder /app/dist /usr/share/nginx/html
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
